name: deploy heroku, publish release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: Release
      - name: DeployHeroku with github secrets
        uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{ secrets.heroku_api_key }}
          heroku_app_name: portfolio-tracker-arian
          heroku_email: ${{ secrets.heroku_email }}
          branch: ${{ github.ref_name }}
        env:
          HD_SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          HD_SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          HD_SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          HD_FINNHUB_API_KEY : ${{secrets.FINNHUB_API_KEY}}